[package]
name = "rustc_codegen_spirv-target-specs"
description = "target spec json files of rust-gpu for the rustc compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
include_str = []
dir_path = []
