[toolchain]
channel = "nightly-2026-09-25"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = f7575a9da8e4a4fca3b5668d5a2ea7476db44b3f

# Whenever changing the nightly channel, update the commit hash above, and
# change `REQUIRED_RUST_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` too.
