[toolchain]
channel = "nightly-2026-04-02"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 7e46c5f6fb87f8cf4353e058479cef15d1d952b4

# Whenever changing the nightly channel, update the commit hash above, and
# change `REQUIRED_RUST_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` too.
