[toolchain]
channel = "nightly-2024-04-24"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 244da22fabd9fa677bbd0ac601a88e5ca6917526

# Whenever changing the nightly channel, also update the commit hash above.
