[profile.default]
default-filter = '!package(difftest*) & !package(compiletest*) & !package(example-runner-*)'
fail-fast = false

[profile.difftests]
default-filter = 'package(difftests)'
slow-timeout = "2m"

[profile.difftest-runner]
default-filter = 'package(difftest-runner) | package(difftest-types)'
