[package]
name = "spirv-std-nightly"
description = "spirv-std but with nightly-only features like adt_const_params"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
spirv-std = { workspace = true, features = ["adt_const_params"] }
spirv-std-macros.workspace = true

[features]
default = ["spirv-std/default"]
bytemuck = ["spirv-std/bytemuck"]
glam_0_33 = ["spirv-std/glam_0_33"]
glam_0_32 = ["spirv-std/glam_0_32"]
glam_0_31 = ["spirv-std/glam_0_31"]
glam_0_30 = ["spirv-std/glam_0_30"]
