name: Release-plz

on:
  push:
    branches:
      - main
      - setup-release2

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    if: ${{ github.repository_owner == 'rust-gpu' }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        # SAFETY REMOVAL
#      - name: Run release-plz
#        uses: release-plz/action@v0.5
#        with:
#          command: release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    if: ${{ github.repository_owner == 'rust-gpu' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - name: release-plz update
        uses: release-plz/action@v0.5
        with:
          command: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update difftest Cargo.lock
        run: cargo fetch --manifest-path=tests/difftests/tests/Cargo.toml
      - name: release-plz release-pr
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
